name: PR Review Agent
description: Automated AI code review for pull requests
url: http://localhost:3000
homepage: https://github.com
version: 1.0.0
default_permissions:
  pull_requests: write
  contents: read
  issues: write
default_events:
  - pull_request
public: false