name: PR Review Agent
url: https://github.com/ForestMars/devi
hook_attributes:
  url: https://smee.io/soupchannel
description: Automated AI code review for pull requests
public: false
default_permissions:
  contents: read
  issues: write
  pull_requests: write
default_events:
  - pull_request